import AppKit
import Defaults
import UniformTypeIdentifiers

/// Polls the general pasteboard and turns new copies into `ClipItem`s.
@MainActor
final class ClipboardMonitor: ObservableObject {
    private let store: ClipStore
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Sticky pause — no new clips until resumed. Survives via Defaults.
    @Published private(set) var isPaused: Bool

    /// Skip the next pasteboard change only (in-memory).
    @Published private(set) var ignoreNextCopy = false

    private var pauseObservation: Defaults.Observation?

    /// Pasteboard types apps use to mark content that shouldn't be recorded.
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",      // passwords (password managers set this)
        "org.nspasteboard.AutoGeneratedType",  // transient/auto-generated
    ]

    init(store: ClipStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
        self.isPaused = Defaults[.clipboardCapturePaused]
        pauseObservation = Defaults.observe(.clipboardCapturePaused) { [weak self] change in
            guard let self else { return }
            MainActor.assumeIsolated {
                guard self.isPaused != change.newValue else { return }
                self.isPaused = change.newValue
                self.lastChangeCount = NSPasteboard.general.changeCount
            }
        }
    }

    func start() {
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func setPaused(_ paused: Bool) {
        guard isPaused != paused else { return }
        isPaused = paused
        Defaults[.clipboardCapturePaused] = paused
        // Advance change count so resume doesn't ingest a backlog of copies.
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func ignoreNext() {
        ignoreNextCopy = true
    }

    deinit { timer?.invalidate() }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if isPaused { return }
        if ignoreNextCopy {
            ignoreNextCopy = false
            return
        }
        capture(from: pb)
    }

    private func capture(from pb: NSPasteboard) {
        let types = pb.types ?? []
        let sensitive = types.contains { Self.concealedTypes.contains($0.rawValue) }
        if sensitive && Defaults[.skipSensitiveContent] { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier,
           Defaults[.ignoredCaptureApps].contains(bid) {
            return
        }

        guard let kind = classify(pb) else { return }

        // Keep an RTF copy of text clips so they can be pasted with formatting
        // (and stripped on demand).
        var richRTF: Data?
        if case .text = kind {
            richRTF = pb.data(forType: .rtf) ?? pb.data(forType: .rtfd)
        }
        let item = ClipItem(
            kind: kind,
            sourceAppName: front?.localizedName,
            sourceAppBundleID: front?.bundleIdentifier,
            isSensitive: sensitive,
            richRTF: richRTF
        )
        store.add(item)
    }

    /// Classify pasteboard content, most specific first.
    private func classify(_ pb: NSPasteboard) -> ClipKind? {
        // 1. File on disk → security-scoped bookmark.
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           let url = urls.first, url.isFileURL {
            let bookmark = (try? url.bookmarkData(options: [.withSecurityScope]))
                ?? (try? url.bookmarkData())
            if let bookmark {
                return .file(bookmark: bookmark, path: url.path, displayName: url.lastPathComponent)
            }
        }

        // 2. Image bitmap.
        if pb.canReadItem(withDataConformingToTypes: [UTType.png.identifier, UTType.tiff.identifier]),
           let image = NSImage(pasteboard: pb), let png = image.pngData() {
            guard let saved = BlobStore.shared.savePNG(png) else { return nil }
            let size = image.pixelSize
            return .image(blobFile: saved.file, contentHash: saved.hash,
                          pixelWidth: Int(size.width), pixelHeight: Int(size.height))
        }

        // 3. A real color object (color picker, etc.).
        if let colors = pb.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor],
           let color = colors.first {
            return .color(hex: color.hexString)
        }

        // 4. A web URL object.
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let url = urls.first, !url.isFileURL {
            return .link(url: url)
        }

        // 5. Plain string — may itself be a hex color or a bare URL.
        if let string = pb.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            if let hex = Self.colorHex(trimmed) { return .color(hex: hex) }
            if !trimmed.contains(" "),
               let url = URL(string: trimmed),
               let scheme = url.scheme?.lowercased(),
               scheme == "http" || scheme == "https" {
                return .link(url: url)
            }
            guard !trimmed.isEmpty else { return nil }
            return .text(string: string)
        }

        return nil
    }

    /// Returns a normalized `#RRGGBB[AA]` string if `s` is a hex color literal.
    static func colorHex(_ s: String) -> String? {
        let pattern = "^#?([0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?)$"
        guard s.range(of: pattern, options: .regularExpression) != nil else { return nil }
        let body = s.hasPrefix("#") ? String(s.dropFirst()) : s
        return "#" + body.uppercased()
    }
}
